### ISSUE TITLE
is pdp still available?

### ISSUE THREAD

**Issue by AlexGaithuma** [widdowquinn/find_differential_primers#48]
I could not install pdp with conda or pip following the instructions in the manual (https://pdp.readthedocs.io/en/diagnostic_primers/quickstart.html)
I tried finding pdp in anaconda packages and in pypi to no success..

my command:

    conda install -c bioconda pdp
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Collecting package metadata (repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.

    PackagesNotFoundError: The following packages are not available from current channels:
      - pdp
    Current channels:
      - https://conda.anaconda.org/bioconda/linux-64
      - https://conda.anaconda.org/bioconda/noarch
      - https://repo.anaconda.com/pkgs/main/linux-64
      - https://repo.anaconda.com/pkgs/main/noarch
      - https://repo.anaconda.com/pkgs/r/linux-64
      - https://repo.anaconda.com/pkgs/r/noarch

    To search for alternate channels that may provide the conda package you're looking for, navigate to
    https://anaconda.org and use the search bar at the top of the page.

I also tried pip

     pip install pdp
     Requirement already satisfied: pdp in ./anaconda3/lib/python3.7/site-packages (0.3.0)

running the command pdp:

     pdp
     No command 'pdp' found, but there are 24 similar ones
     pdp: command not found
I found out that the pdp that was installed was an interface package to organize pipelines of data processing.

**Comment by dswan** [comment]
I think that you still have to install pdp from the git repository:

```
$ git clone https://github.com/widdowquinn/find_differential_primers
$ cd find_differential_primers
$ python setup.py install
```

**Comment by widdowquinn** [comment]
Hi Alex,

Thanks for trying `pdp`/`find_differential_primers`.

`pdp` is available, but there is a stable version (`find_differential_primers`) and a development version (`pdp`).

I don't know where Dan's comment went (I got an email notification but can't see it here) but he was correct: `pdp` is not currently available *via* `conda`, and you have to install from source. As noted [here](https://github.com/widdowquinn/find_differential_primers/blob/diagnostic_primers/README.md) `pdp` is on the development branch, not the stable version. It has new features, but isn't ready for formal release, yet. It does work well enough to design diagnostic primers, though.

If you need to install *via* `conda`, then the older, stable version is [available](https://anaconda.org/bioconda/find_differential_primers), and the relevant documentation for usage is [here](https://github.com/widdowquinn/find_differential_primers/blob/master/README.md).

I hope this helps, but please do raise further questions as issues.

L.
