### ISSUE TITLE
conda install pdp not working

### ISSUE THREAD

**Issue by rsiani** [widdowquinn/find_differential_primers#49]
Hi,
I have been trying to install your software, however it seems like pdp is no longer on anaconda? I was able to find your old version find_differential_primers on bioconda, but not the new one.

**Comment by widdowquinn** [comment]
Hi @rsiani - I'm afraid that `pdp` has not yet been made available *via* `conda`. The only version available there at the moment is `find_differential_primers`.

Apologies for the inconvenience.

L.
